### ISSUE TITLE
Source script instead of piping to bash.

### ISSUE THREAD

**Issue by jkutner** [heroku/exec-buildpack#1]
change the `heroku-exec.sh.erb` script to this:

```bash
if [ -n "$HEROKU_EXEC_URL" ]; then
  [ -z "$SSH_CLIENT" ] && source <(curl --retry 3 -sSL $HEROKU_EXEC_URL)
fi
```

The difference is sourcing the output of curl instead of piping it to bash. This allows us to set additional env vars from the HEROKU_EXEC_URL.

**Comment by pepa65** [comment]
Why would you not be able to set those environment variables when piping into bash?? Doesn't it come down to the same thing?

**Comment by jkutner** [comment]
@pepa65 you can't `export` env vars without `source`, which makes them available to other processes. This is needed for `JAVA_TOOL_OPTIONS` for Java specific tooling.

**Comment by pepa65** [comment]
Thanks for responding. I see now that piping into bash starts a new shell for that process, and exported variables will be lost when it ends.
